version: "3.3"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data/
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000

volumes:
    db_data: