"""update saving month-year-user_id constraint

Revision ID: 10dc772d2f49
Revises: c87fc969724c
Create Date: 2022-07-14 15:04:45.814492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dc772d2f49'
down_revision = 'c87fc969724c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('month_year_unique', 'saving', type_='unique')
    op.create_unique_constraint('month_year_user_unique', 'saving', ['month', 'year', 'member_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('month_year_user_unique', 'saving', type_='unique')
    op.create_unique_constraint('month_year_unique', 'saving', ['month', 'year'])
    # ### end Alembic commands ###
