"""an instalment is unique for month and loan_id

Revision ID: be4a02db9f3d
Revises: ba9d6e71a5b5
Create Date: 2022-05-23 05:53:01.845482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4a02db9f3d'
down_revision = 'ba9d6e71a5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('month_loan_unique', 'instalment', ['month', 'loan_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('month_loan_unique', 'instalment', type_='unique')
    # ### end Alembic commands ###
