"""add loan restructure

Revision ID: c87fc969724c
Revises: be4a02db9f3d
Create Date: 2022-05-25 12:41:27.614473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87fc969724c'
down_revision = 'be4a02db9f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('restructured_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loan', 'loan', ['restructured_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_column('loan', 'restructured_to_id')
    # ### end Alembic commands ###
